source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.5'
gem 'rails', '~> 6.1.7'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'
# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem 'bx_block_roles_permissions-c50949d0', '1.3.0', require: 'bx_block_roles_permissions'
gem 'account_block', '1.3.0', require: 'account_block'
gem 'bx_block_sms', '1.1.0'
gem 'bx_block_navmenu-1cdc25a4', '1.2.1', require: 'bx_block_navmenu'
gem 'bx_block_login-3d0582b5', '1.1.1', require: 'bx_block_login'
gem 'bx_block_forgot_password-4de8968b', '1.1.1', require: 'bx_block_forgot_password'
gem 'bx_block_admin', '1.3.0'
gem 'bx_block_location-99004202', '0.0.10', require: 'bx_block_location'
gem 'bx_block_address-07f1bf4f', '1.3.0', require: 'bx_block_address'
gem 'bx_block_appointment_management-eb816fd3', '1.3.0', require: 'bx_block_appointment_management'
gem 'bx_block_account_groups', '1.3.0', require: 'bx_block_account_groups'
gem 'bx_block_terms_and_conditions', '1.3.0', require: 'bx_block_terms_and_conditions'
gem 'bx_block_settings-5412d427', '1.2.1', require: 'bx_block_settings'
gem 'bx_block_content_management', '0.1.3'

gem 'bx_block_categories-acd0763f', '1.3.0', require: 'bx_block_categories'
gem 'bx_block_advanced_search-23b25188', '1.1.1', require: 'bx_block_advanced_search'
gem 'bx_block_custom_form-63cd533b', '1.3.0', require: 'bx_block_custom_form'
gem 'bx_block_photo_library-6419d914', '1.2.1', require: 'bx_block_photo_library'
gem 'bx_block_contact_us-6e0a750f', '1.3.0', require: 'bx_block_contact_us'
gem 'bx_block_profile', '1.3.0', require: 'bx_block_profile'
gem 'bx_block_upload_media-9de56634', '1.3.0', require: 'bx_block_upload_media'
gem 'bx_block_custom_ads-e8d68990', '1.3.0', require: 'bx_block_custom_ads'
gem 'bx_block_profile_bio', '1.3.0', require: 'bx_block_profile_bio'
gem 'bx_block_profile_lite', '0.3.0', require: 'bx_block_profile'
gem 'bx_block_custom_forms', '0.4.0', require: 'bx_block_custom_forms'
gem 'bx_block_catalogue-0e5da613', '1.3.0', require: 'bx_block_catalogue'
gem 'bx_block_filter_items-b1be1f37', '1.1.1', require: 'bx_block_filter_items'

gem 'builder_base', '1.4.0'

group :development, :test do
    gem 'rspec-sonarqube-formatter', '1.5.0'
    gem 'rspec-rails', '5.1.2'
    gem 'simplecov', '0.17.0'
    gem 'factory_bot_rails', '6.2.0'
    gem 'letter_opener'
    gem 'dotenv'
    gem 'rails-controller-testing'
end

group :test do
  gem 'mock_redis', '0.34.0'
  gem 'selenium-webdriver', '~> 4.0.3'
  gem 'shoulda-matchers'
end

gem 'sidekiq_alive'
gem 'sidekiq', '~> 6.1.0'
gem "sidekiq-cron"

gem "yabeda-prometheus"    # Base
gem "yabeda-rails"         #API endpoint monitoring
gem "yabeda-http_requests" #External request monitoring
gem "yabeda-puma-plugin"
gem 'yabeda-sidekiq'

gem 'bx_block_cors'
gem 'devise'
gem 'sassc-rails'
gem 'activeadmin'
gem 'active_admin_role'
gem 'activeadmin_json_editor'
gem 'active_admin_datetimepicker'
gem 'rack-cors'
gem 'activestorage-validator'
gem 'will_paginate'
gem 'kaminari'
gem 'zip-codes'
gem "capybara"
gem 'activeadmin_quill_editor', '~> 1.0.0' 
gem 'arctic_admin'
gem 'faker'
gem 'geocoder'
gem 'aws-sdk-s3'
gem 'rest-client'
gem 'aasm'
gem 'stripe'
gem 'sinatra'

gem 'bx_block_educational_gamification', '1.2.0'
gem 'bx_block_performance_tracker', '1.3.0', require: 'bx_block_performance_tracker'
gem 'bx_block_salesforceintegration2', '0.2.0'
gem 'bx_block_order_management-674a3e38', '1.3.0', require: 'bx_block_order_management'
# gem 'bx_block_stripe_order_management', '0.4.0'

gem 'bx_block_coupon_cg-1da92412', '0.0.1', require: 'bx_block_coupon_cg'
gem 'bx_block_fedex_integration-c7604a00', '1.3.0', require: 'bx_block_fedex_integration'
gem 'bx_block_stripe_integration', '2.2.0', require: 'bx_block_stripe_integration'
gem 'bx_block_followers-ea7cb581', '1.2.1', require: 'bx_block_followers'
gem 'bx_block_visual_analytics', '1.1.0'
gem 'bx_block_custom_user_subs', '0.0.9'
gem 'bx_block_automatic_renewals-0b2de503', '1.2.1', require: 'bx_block_automatic_renewals'
gem 'bx_block_posts-3dc5b993', '1.2.1', require: 'bx_block_posts'
gem 'bx_block_share', '1.3.0', require: 'bx_block_share'
gem 'bx_block_calendar-4836ef12', '1.1.1', require: 'bx_block_calendar'
gem 'bx_block_scheduling-d1f08754', '1.1.1', require: 'bx_block_scheduling'
gem 'bx_block_like_a_post-27907772', '0.0.6', require: 'bx_block_like_a_post'

gem 'bx_block_push_notifications-c0f9e9b7', '1.3.0', require: 'bx_block_push_notifications'
gem 'bx_block_like', '1.2.0'
gem 'bx_block_subscription_billing', '1.2.0'
gem 'active_storage_validations', '~> 1.0.4'
gem 'city-state'
gem 'htmlentities'
gem 'activeadmin-searchable_select'
gem 'rubyzip', '>= 1.2.2'
gem 'mini_magick'
gem 'image_processing'
gem 'net-imap', '0.3.7'
gem 'nokogiri', '1.13.10'
gem 'zeitwerk', '~> 2.3'
gem 'concurrent-ruby', '1.3.4'
gem 'timezone', '~> 1.0'